### ISSUE TITLE
GitLab Backend suddenly produces blocking error

### ISSUE THREAD

**Issue by RoiArthurB** [ananace/matrix-releasetracker#10]
Everything was running well in a perfect world, then one day the bot stopped working (very sad).

After checking the logs, I discovered that an error is produced by the Gitlab backend blocking the rest of the bot with this error : 

```
[2023-06-01 15:14:44|E] Releasetracker: Failed to run updates for room !XXX:domain.com, NoMethodError: undefined method `map' for nil:NilClass
/opt/matrix-releasetracker/lib/matrix_releasetracker/backends/gitlab.rb:150:in `find_gql_releases'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backends/gitlab.rb:50:in `find_repo_releases'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:285:in `grab_repository_releases'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:331:in `grab_repository'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:243:in `last_repo_release'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:137:in `last_releases'
bin/tracker:90:in `block in calculate_to_track'
bin/tracker:88:in `map'
bin/tracker:88:in `calculate_to_track'
bin/tracker:108:in `block in update_backends'
bin/tracker:106:in `each'
```

I tried updating every Personal Access Token, removing specific domains, etc; but the only solution is to disable this backend :/

Here's snippets of config files I tried : 

```
- :access_token: '???'
  :type: :github
- :type: :gitlab
- :type: :gitea
```

```
- :access_token: '???'
  :type: :github
- :type: :gitlab
  # For tracking non-public data or users (stars)
  :instances:
    'gitlab.com':
      :token: 'XXX'
    'dev.funkwhale.audio':
      :token: 'YYY'
    'mau.dev':
      :token: 'ZZZ'
- :type: :gitea
```

```
- :access_token: '???'
  :type: :github
- :type: :gitlab
  # For tracking non-public data or users (stars)
  :instances:
    'gitlab.com':
      :token: 'XXX'
- :type: :gitea
```

**Comment by ananace** [comment]
Guess GitLab have changed something in their GraphQL API, I'll have a look at it.

**Comment by RoiArthurB** [comment]
Thanks :partying_face:
