### ISSUE TITLE
Some un-implemented function prevents software from working

### ISSUE THREAD

**Issue by RoiArthurB** [ananace/matrix-releasetracker#4]
From the very last commit on the `master` branch, there's some function un-implemented which are preventing the full software to run, see logs :

```
dietpi@DietPi:/opt/matrix-releasetracker$ bundle exec bin/tracker 
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
[2022-07-20 09:24:23|I] Releasetracker: Loaded configuration.
[2022-07-20 09:24:23|I] Releasetracker: Ensuring configured rooms are joined.
[2022-07-20 09:24:27|I] Releasetracker: Starting tracker with 4 backends.
[2022-07-20 09:24:27|I] Releasetracker: Starting Matrix sync loop...
bundler: failed to load command: bin/tracker (bin/tracker)
Traceback (most recent call last):
	26: from /usr/local/bin/bundle:23:in `<main>'
	25: from /usr/local/bin/bundle:23:in `load'
	24: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
	23: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	22: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
	21: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
	20: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	19: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
	18: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	17: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	16: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	15: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
	14: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
	13: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
	12: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
	11: from bin/tracker:336:in `<top (required)>'
	10: from bin/tracker:55:in `run!'
	9: from bin/tracker:106:in `update_backends'
	8: from bin/tracker:106:in `each'
	7: from bin/tracker:108:in `block in update_backends'
	6: from bin/tracker:88:in `calculate_to_track'
	5: from bin/tracker:88:in `map'
	4: from bin/tracker:90:in `block in calculate_to_track'
	3: from /opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:129:in `last_releases'
	2: from /opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:397:in `refresh_tracked'
	1: from /opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:417:in `refresh_group'
/opt/matrix-releasetracker/lib/matrix_releasetracker/backend.rb:177:in `find_group_repositories': NotImplementedError (NotImplementedError)
```

**Comment by ananace** [comment]
I'll need to really improve the error handling, that's for certain. And probably also figure out a good point for notifying a user if there's issues in actually acting on their tracking requests - not just if there are issues on the requests themself.
